const BUYER_PRIVATE_INFO_DELETION = {
  NEVER: 'NEVER',
  INSTANTLY: 'INSTANTLY',
  DAY: 'DAY',
  THREE_DAYS: 'THREE_DAYS',
  WEEK: 'WEEK',
  MONTH: 'MONTH',
};

module.exports = { BUYER_PRIVATE_INFO_DELETION };
