const ORDER_STATUS = {
  AWAITING_INFORMATION: 'AWAITING_INFORMATION',
  AWAITING_PAYMENT: 'AWAITING_PAYMENT',
  AWAITING_SHIPMENT: 'AWAITING_SHIPMENT',
  SHIPPED: 'SHIPPED',
  RECEIVED: 'RECEIVED',
  REJECTED: 'REJECTED',
  FINALIZED: 'FINALIZED',
  DISPUTED: 'DISPUTED',
  DISPUTE_IN_PROGRESS: 'DISPUTE_IN_PROGRESS',
  EXPIRED: 'EXPIRED',
};

module.exports = { ORDER_STATUS };
